"""XML BOM/manifest writer round-trip and structural tests."""

from __future__ import annotations

import math
from pathlib import Path

import pytest

from manufacturing_pipeline.classification.types import (
    ClassificationResult,
    Contribution,
    DecisionTrace,
)
from manufacturing_pipeline.geometry.types import (
    HolePattern,
    ManufacturingFeatures,
    ProfileMatch,
    UnfoldResult,
    UnfoldStatus,
)
from manufacturing_pipeline.io.xml_writer import (
    NAMESPACE,
    AssemblyManifest,
    ManifestParseError,
    PartManifestEntry,
    read_xml,
    write_xml,
)
from manufacturing_pipeline.parsing.types import StepPart

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _approx(a: float, b: float, *, rel: float = 1e-12, abs_: float = 0.0) -> bool:
    return math.isclose(a, b, rel_tol=rel, abs_tol=abs_)


def _full_classification() -> ClassificationResult:
    trace = DecisionTrace(
        scores={"plaat": 1.42, "profiel": 0.31, "anders": 0.18},
        probabilities={"plaat": 0.71, "profiel": 0.18, "anders": 0.11},
        margin=1.11,
        ambiguous=False,
        contributions=[
            Contribution(feature="top1_face_pct", cls="plaat", value=0.78, delta=0.62),
            Contribution(feature="aspect_ratio", cls="profiel", value=9.0, delta=0.31),
        ],
        tiebreakers_run=["unfold_tiebreaker"],
        probe_results={"unfoldable": "true"},
        model_version="rules-1.0.0",
    )
    return ClassificationResult(label="plaat", confidence=0.91, trace=trace)


def _full_features() -> ManufacturingFeatures:
    return ManufacturingFeatures(
        volume=123456.0,
        surface_area=45678.0,
        bbox_dims_sorted=(200.0, 100.0, 2.0),
        aspect_ratio=2.0,
        thickness_ratio=0.01,
        face_area_top=[0.78, 0.15, 0.05],
        surface_pct={"planar": 0.97, "cylindrical": 0.03},
        edge_counts={"linear": 12, "circular": 4},
        edge_radius=(1.5, 0.25),
        hole_count=4,
        hole_diameters=[10.0, 10.0, 8.0, 8.0],
        sa_v_ratio=0.37,
        bounding_cylinder_fit_pct=0.42,
        convex_hull_volume_ratio=0.95,
        cross_section_constant=False,
        cross_section_signature={"hash": "abc123"},
        is_hollow=False,
        inner_shell_count=0,
        source="brep",
    )


def _full_profile_match() -> ProfileMatch:
    return ProfileMatch(
        family="HEA",
        standard="DIN 1025-3",
        designation="HEA 200",
        fitted_dims={"h": 190.0, "b": 200.0, "tw": 6.5, "tf": 10.0},
        residual_mm=0.42,
        confidence=0.85,
    )


def _full_unfold() -> UnfoldResult:
    return UnfoldResult(
        status=UnfoldStatus.SUCCESS,
        n_bends=2,
        flat_area=18234.5,
        blank_bbox=(250.0, 120.0),
        thickness_mean=2.0,
        thickness_cv=0.01,
        flags={"has_hem": False, "has_complex_bend": False},
        reason="",
    )


def _full_holes() -> HolePattern:
    return HolePattern(hole_count=4, diameters=[10.0, 10.0, 8.0, 8.0])


def _full_part(name: str = "Front Bracket", product_id: str = "ASM-0042-12") -> StepPart:
    return StepPart(
        product_id=product_id,
        name=name,
        description="Stainless plaat",
        children=["#1234"],
        source="nauo",
    )


def _full_manifest(tmp_path: Path) -> AssemblyManifest:
    return AssemblyManifest(
        source_path=str(tmp_path / "asm.stp"),
        source_mtime=1734567890.0,
        source_size=123456,
        model_version="rules-1.0.0",
        generated_at="2026-05-15T12:00:00Z",
        parts=[
            PartManifestEntry(
                part=_full_part(),
                classification=_full_classification(),
                features=_full_features(),
                profile_match=_full_profile_match(),
                unfold=_full_unfold(),
                holes=_full_holes(),
                quantity=2,
                flat_dxf_path="parts/front_bracket.dxf",
            )
        ],
        notes="auto-generated by analyze_assembly",
    )


# ---------------------------------------------------------------------------
# Test 1: full round-trip
# ---------------------------------------------------------------------------


def test_round_trip_full_manifest(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    out = write_xml(manifest, tmp_path / "manifest.xml")
    parsed = read_xml(out)

    assert parsed.source_path == manifest.source_path
    assert _approx(parsed.source_mtime, manifest.source_mtime)
    assert parsed.source_size == manifest.source_size
    assert parsed.model_version == manifest.model_version
    assert parsed.generated_at == manifest.generated_at
    assert parsed.notes == manifest.notes
    assert len(parsed.parts) == 1

    op = manifest.parts[0]
    pp = parsed.parts[0]
    assert pp.part == op.part
    assert pp.quantity == op.quantity
    assert pp.flat_dxf_path == op.flat_dxf_path

    # Classification
    assert pp.classification.label == op.classification.label
    assert _approx(pp.classification.confidence, op.classification.confidence)
    for cls_name, val in op.classification.trace.scores.items():
        assert _approx(pp.classification.trace.scores[cls_name], val)
    for cls_name, val in op.classification.trace.probabilities.items():
        assert _approx(pp.classification.trace.probabilities[cls_name], val)
    assert _approx(pp.classification.trace.margin, op.classification.trace.margin)
    assert pp.classification.trace.ambiguous == op.classification.trace.ambiguous
    assert pp.classification.trace.tiebreakers_run == op.classification.trace.tiebreakers_run
    assert pp.classification.trace.probe_results == op.classification.trace.probe_results
    assert pp.classification.trace.model_version == op.classification.trace.model_version
    assert len(pp.classification.trace.contributions) == len(op.classification.trace.contributions)
    for parsed_c, orig_c in zip(
        pp.classification.trace.contributions, op.classification.trace.contributions
    ):
        assert parsed_c.feature == orig_c.feature
        assert parsed_c.cls == orig_c.cls
        assert _approx(parsed_c.value, orig_c.value)
        assert _approx(parsed_c.delta, orig_c.delta)

    # Features
    assert pp.features is not None and op.features is not None
    assert _approx(pp.features.volume, op.features.volume)
    assert _approx(pp.features.surface_area, op.features.surface_area)
    for pa, oa in zip(pp.features.bbox_dims_sorted, op.features.bbox_dims_sorted):
        assert _approx(pa, oa)
    assert _approx(pp.features.aspect_ratio, op.features.aspect_ratio)
    assert _approx(pp.features.thickness_ratio, op.features.thickness_ratio)
    assert pp.features.face_area_top == op.features.face_area_top
    assert pp.features.surface_pct == op.features.surface_pct
    assert pp.features.edge_counts == op.features.edge_counts
    assert pp.features.edge_radius == op.features.edge_radius
    assert pp.features.hole_count == op.features.hole_count
    assert pp.features.hole_diameters == op.features.hole_diameters
    assert _approx(pp.features.sa_v_ratio, op.features.sa_v_ratio)
    assert pp.features.is_hollow == op.features.is_hollow
    assert pp.features.inner_shell_count == op.features.inner_shell_count
    assert pp.features.source == op.features.source

    # Profile match
    assert pp.profile_match is not None and op.profile_match is not None
    assert pp.profile_match.family == op.profile_match.family
    assert pp.profile_match.standard == op.profile_match.standard
    assert pp.profile_match.designation == op.profile_match.designation
    assert pp.profile_match.fitted_dims == op.profile_match.fitted_dims
    assert _approx(pp.profile_match.residual_mm, op.profile_match.residual_mm)
    assert _approx(pp.profile_match.confidence, op.profile_match.confidence)

    # Unfold
    assert pp.unfold is not None and op.unfold is not None
    assert pp.unfold.status == op.unfold.status
    assert pp.unfold.n_bends == op.unfold.n_bends
    assert _approx(pp.unfold.flat_area, op.unfold.flat_area)
    assert pp.unfold.blank_bbox == op.unfold.blank_bbox
    assert _approx(pp.unfold.thickness_mean, op.unfold.thickness_mean)
    assert _approx(pp.unfold.thickness_cv, op.unfold.thickness_cv)
    assert pp.unfold.flags == op.unfold.flags

    # Holes
    assert pp.holes is not None and op.holes is not None
    assert pp.holes.hole_count == op.holes.hole_count
    assert pp.holes.diameters == op.holes.diameters


# ---------------------------------------------------------------------------
# Test 2: minimal second part (classification only)
# ---------------------------------------------------------------------------


def test_round_trip_two_parts_one_minimal(tmp_path: Path):
    minimal_trace = DecisionTrace(
        scores={"plaat": 0.1, "profiel": 0.0, "anders": 0.9},
        probabilities={"plaat": 0.1, "profiel": 0.0, "anders": 0.9},
        margin=0.8,
        ambiguous=False,
        contributions=[],
        tiebreakers_run=[],
        probe_results={},
        model_version="rules-1.0.0",
    )
    minimal_part = PartManifestEntry(
        part=StepPart(product_id="X-1", name="bolt", description="", children=[], source="nauo"),
        classification=ClassificationResult("anders", 0.9, minimal_trace),
    )

    full = _full_manifest(tmp_path)
    full.parts.append(minimal_part)
    out = write_xml(full, tmp_path / "manifest.xml")
    parsed = read_xml(out)

    assert len(parsed.parts) == 2
    m = parsed.parts[1]
    assert m.features is None
    assert m.profile_match is None
    assert m.unfold is None
    assert m.holes is None
    assert m.flat_dxf_path is None
    assert m.part.product_id == "X-1"
    assert m.classification.label == "anders"


# ---------------------------------------------------------------------------
# Test 3: UTF-8 + special chars
# ---------------------------------------------------------------------------


def test_utf8_and_special_chars_round_trip(tmp_path: Path):
    part = StepPart(
        product_id="UMLAUT-1",
        name='Ühlbrück "Spëcial" Steël & Co. <plate>',
        description="Bréf é à ö ü plaat",
        children=[],
        source="nauo",
    )
    trace = DecisionTrace(
        scores={"plaat": 1.0, "profiel": 0.0, "anders": 0.0},
        probabilities={"plaat": 1.0, "profiel": 0.0, "anders": 0.0},
        margin=1.0,
        ambiguous=False,
        contributions=[],
        tiebreakers_run=[],
        probe_results={},
        model_version="rules-1.0.0",
    )
    manifest = AssemblyManifest(
        source_path="/tmp/Ünëf.stp",
        source_mtime=1.0,
        source_size=1,
        model_version="rules-1.0.0",
        generated_at="2026-05-15T12:00:00Z",
        parts=[
            PartManifestEntry(part=part, classification=ClassificationResult("plaat", 1.0, trace))
        ],
        notes="ä ö é ü <weird & stuff>",
    )
    out = write_xml(manifest, tmp_path / "utf8.xml")
    raw = out.read_bytes()
    # Verify encoded as UTF-8 and the umlauts survive end-to-end.
    assert b"<?xml" in raw
    parsed = read_xml(out)
    assert parsed.parts[0].part.name == part.name
    assert parsed.parts[0].part.description == part.description
    assert parsed.notes == manifest.notes


# ---------------------------------------------------------------------------
# Test 4: schema basics
# ---------------------------------------------------------------------------


def test_schema_root_namespace_and_attributes(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    out = write_xml(manifest, tmp_path / "manifest.xml")

    import xml.etree.ElementTree as ET

    tree = ET.parse(out)
    root = tree.getroot()
    assert root.tag == f"{{{NAMESPACE}}}assembly"
    for required in ("source", "source-mtime", "source-size", "generated-at", "model-version"):
        assert required in root.attrib, f"missing required attr {required}"


# ---------------------------------------------------------------------------
# Test 5: pretty-printing
# ---------------------------------------------------------------------------


def test_pretty_printing_produces_indentation(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    out = write_xml(manifest, tmp_path / "pretty.xml", pretty=True)
    text = out.read_text(encoding="utf-8")
    assert "\n    " in text  # 4-space-deep indent (2 levels * 2 spaces)
    assert "\n" in text

    out2 = write_xml(manifest, tmp_path / "compact.xml", pretty=False)
    compact = out2.read_text(encoding="utf-8")
    # Compact output should not have those indents.
    assert "\n    " not in compact


# ---------------------------------------------------------------------------
# Test 6: malformed XML
# ---------------------------------------------------------------------------


def test_malformed_xml_raises(tmp_path: Path):
    bad = tmp_path / "broken.xml"
    bad.write_text("<assembly><parts><part></parts></assembly>", encoding="utf-8")
    with pytest.raises(ManifestParseError):
        read_xml(bad)


def test_wrong_root_element_raises(tmp_path: Path):
    bad = tmp_path / "wrong_root.xml"
    bad.write_text('<?xml version="1.0"?><not-an-assembly/>', encoding="utf-8")
    with pytest.raises(ManifestParseError):
        read_xml(bad)


# ---------------------------------------------------------------------------
# Test 7: empty manifest
# ---------------------------------------------------------------------------


def test_empty_manifest_round_trips(tmp_path: Path):
    manifest = AssemblyManifest(
        source_path="/tmp/empty.stp",
        source_mtime=0.0,
        source_size=0,
        model_version="rules-1.0.0",
        generated_at="2026-05-15T12:00:00Z",
        parts=[],
        notes="",
    )
    out = write_xml(manifest, tmp_path / "empty.xml")
    parsed = read_xml(out)
    assert parsed.parts == []
    assert parsed.notes == ""
    assert parsed.source_path == "/tmp/empty.stp"


# ---------------------------------------------------------------------------
# Test 8: flat-dxf presence/absence
# ---------------------------------------------------------------------------


def test_flat_dxf_omitted_when_none(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    manifest.parts[0].flat_dxf_path = None
    out = write_xml(manifest, tmp_path / "no_dxf.xml")
    text = out.read_text(encoding="utf-8")
    assert "<flat-dxf" not in text

    parsed = read_xml(out)
    assert parsed.parts[0].flat_dxf_path is None


def test_flat_dxf_present_when_set(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    manifest.parts[0].flat_dxf_path = "parts/foo.dxf"
    out = write_xml(manifest, tmp_path / "with_dxf.xml")
    text = out.read_text(encoding="utf-8")
    assert 'path="parts/foo.dxf"' in text
    parsed = read_xml(out)
    assert parsed.parts[0].flat_dxf_path == "parts/foo.dxf"


# ---------------------------------------------------------------------------
# Test 9: ProfileMatch with None designation
# ---------------------------------------------------------------------------


def test_profile_match_no_designation_round_trips(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    pm = manifest.parts[0].profile_match
    assert pm is not None
    pm.designation = None
    out = write_xml(manifest, tmp_path / "no_designation.xml")
    text = out.read_text(encoding="utf-8")
    # designation attr should be omitted from <profile-match> when None
    # (note: 'designation' must not appear as an attribute of <profile-match>)
    assert "designation=" not in text.split("<profile-match")[1].split(">")[0]

    parsed = read_xml(out)
    assert parsed.parts[0].profile_match is not None
    assert parsed.parts[0].profile_match.designation is None
    # Other fields still survive
    assert parsed.parts[0].profile_match.family == "HEA"


# ---------------------------------------------------------------------------
# Test 10: UnfoldResult flags dict round-trips
# ---------------------------------------------------------------------------


def test_unfold_flags_round_trip(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    assert manifest.parts[0].unfold is not None
    manifest.parts[0].unfold.flags = {
        "has_hem": True,
        "has_complex_bend": False,
        "max_bend_angle_deg": "175.0",
    }
    out = write_xml(manifest, tmp_path / "flags.xml")
    parsed = read_xml(out)
    flags = parsed.parts[0].unfold.flags  # type: ignore[union-attr]
    assert flags["has_hem"] is True
    assert flags["has_complex_bend"] is False
    assert flags["max_bend_angle_deg"] == "175.0"


# ---------------------------------------------------------------------------
# Bonus: XML declaration / encoding
# ---------------------------------------------------------------------------


def test_xml_declaration_and_utf8_header(tmp_path: Path):
    manifest = _full_manifest(tmp_path)
    out = write_xml(manifest, tmp_path / "header.xml")
    raw = out.read_bytes()
    # ET emits the encoding name in lowercase
    assert raw.startswith(b"<?xml") and b"utf-8" in raw[:80].lower()
