"""Inline SVG renderer for flat-pattern DXF files.

Walks ``LWPOLYLINE`` and ``LINE`` entities on the layers produced by
:mod:`manufacturing_pipeline.io.dxf_writer` (``OUTER``, ``INNER``,
``BEND_UP``, ``BEND_DOWN``) and emits a self-contained SVG document. The
viewBox is auto-fitted around all extracted coordinates so the result fills
the supplied ``width`` x ``height`` canvas without external CSS.

Pure-Python; depends only on ``ezdxf`` and the standard library. SVG is
generated by string concatenation rather than ``xml.etree`` so floating-point
formatting and ordering remain predictable for the test suite.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

import ezdxf

# Layers we render; map -> (svg stroke colour, stroke dasharray or None).
_LAYER_STYLES: dict[str, tuple[str, str | None]] = {
    "OUTER": ("#d62728", None),
    "INNER": ("#2ca02c", None),
    "BEND_UP": ("#1f77b4", "4 2"),
    "BEND_DOWN": ("#ff7f0e", "4 2"),
}

_RENDERABLE_LAYERS = set(_LAYER_STYLES.keys())


def _style_for(layer: str) -> tuple[str, str | None]:
    return _LAYER_STYLES.get(layer, ("#666666", None))


def _polyline_points(entity) -> list[tuple[float, float]]:
    """Extract 2D points from an LWPOLYLINE."""
    return [(float(x), float(y)) for (x, y, *_rest) in entity.get_points("xy")]


def _line_points(entity) -> list[tuple[float, float]]:
    start = entity.dxf.start
    end = entity.dxf.end
    return [(float(start[0]), float(start[1])), (float(end[0]), float(end[1]))]


def _bbox(points_lists: Iterable[list[tuple[float, float]]]) -> tuple[float, float, float, float]:
    xs: list[float] = []
    ys: list[float] = []
    for pts in points_lists:
        for x, y in pts:
            xs.append(x)
            ys.append(y)
    if not xs:
        # Sensible default — never zero-area.
        return (0.0, 0.0, 100.0, 100.0)
    return (min(xs), min(ys), max(xs), max(ys))


def _fmt(n: float) -> str:
    """Format a coordinate for SVG: stable, compact, no trailing zeros."""
    if n == 0:
        return "0"
    s = f"{n:.4f}".rstrip("0").rstrip(".")
    return s or "0"


def dxf_to_svg(
    path: str | Path,
    *,
    width: int = 600,
    height: int = 400,
) -> str:
    """Read a DXF file and return an SVG XML document as a string.

    Only entities on the OUTER / INNER / BEND_UP / BEND_DOWN layers are
    emitted; everything else (annotation text, info headers, helpers) is
    ignored so the preview shows only the cuttable geometry.

    The viewBox is computed from the actual coordinates and flipped along Y
    so the model-space (CAD, +Y up) renders correctly in SVG-space (+Y down).
    """
    p = Path(path)
    doc = ezdxf.readfile(p)
    msp = doc.modelspace()

    closed_polys: list[tuple[str, list[tuple[float, float]], bool]] = []
    open_polys: list[tuple[str, list[tuple[float, float]]]] = []

    for entity in msp.query("LWPOLYLINE LINE"):
        layer = entity.dxf.layer
        if layer not in _RENDERABLE_LAYERS:
            continue
        if entity.dxftype() == "LWPOLYLINE":
            pts = _polyline_points(entity)
            if not pts:
                continue
            closed = bool(getattr(entity, "closed", False))
            closed_polys.append((layer, pts, closed))
        else:  # LINE
            pts = _line_points(entity)
            open_polys.append((layer, pts))

    all_points = [pts for (_, pts, _c) in closed_polys] + [pts for (_, pts) in open_polys]
    xmin, ymin, xmax, ymax = _bbox(all_points)

    # Pad bbox a little so strokes near the edge are not clipped.
    pad = max((xmax - xmin), (ymax - ymin)) * 0.02 or 1.0
    xmin -= pad
    ymin -= pad
    xmax += pad
    ymax += pad

    vb_w = xmax - xmin
    vb_h = ymax - ymin
    if vb_w <= 0:
        vb_w = 1.0
    if vb_h <= 0:
        vb_h = 1.0

    # Decide stroke width relative to viewBox so lines are always visible.
    stroke_w = max(vb_w, vb_h) * 0.0035

    parts: list[str] = []
    parts.append('<?xml version="1.0" encoding="UTF-8"?>')
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{int(width)}" height="{int(height)}" '
        f'viewBox="{_fmt(xmin)} {_fmt(ymin)} {_fmt(vb_w)} {_fmt(vb_h)}" '
        f'preserveAspectRatio="xMidYMid meet">'
    )
    # Flip Y so CAD-space (+Y up) renders right-side-up.
    parts.append(
        f'<g transform="translate(0,{_fmt(ymin + ymax)}) scale(1,-1)" '
        f'fill="none" stroke-width="{_fmt(stroke_w)}" '
        'stroke-linejoin="round" stroke-linecap="round">'
    )

    for layer, pts, closed in closed_polys:
        stroke, dash = _style_for(layer)
        d = " ".join(f"{_fmt(x)},{_fmt(y)}" for (x, y) in pts)
        dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
        if closed:
            parts.append(
                f'<polygon class="layer-{layer}" points="{d}" stroke="{stroke}"{dash_attr} />'
            )
        else:
            parts.append(
                f'<polyline class="layer-{layer}" points="{d}" stroke="{stroke}"{dash_attr} />'
            )

    for layer, pts in open_polys:
        stroke, dash = _style_for(layer)
        d = " ".join(f"{_fmt(x)},{_fmt(y)}" for (x, y) in pts)
        dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
        parts.append(
            f'<polyline class="layer-{layer}" points="{d}" stroke="{stroke}"{dash_attr} />'
        )

    parts.append("</g>")
    parts.append("</svg>")
    return "\n".join(parts)


__all__ = ["dxf_to_svg"]
